### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sitek94** [sitek94/mac-setup#1]
- homebrew casks
  - [ ] arc
  - [ ] obs
- npm packages
  - [ ] pnpm
- post install, manual steps (that could be possibly automated)
  - [ ] download and install Logtech driver, then login to sync settings
  - [ ] BetterTouchTool: give permissions, import presets (dotfiles), import license (1Pass)
  - [ ] KarabinerElements: give permissions, then complex Modifications > map capslock to powerkey
  - [ ] Alfred: give permissions, replace spotlight on `cmd + space` with alfred 
  - [ ] Obsidian: copy notes from iCloud/documents and create vault
  - [ ] ssh-keys
    - [ ] [github](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

  
  

---

template

**Comment by sitek94** [comment]
created dedicated `TODO.md` file because it's easier for me to add new stuff there directly from VSCode
